{{- range .Values.tenants }}
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: {{ .name }}
spec:
  owners:
    - name: system:serviceaccount:argocd:argocd-server
      kind: ServiceAccount
  namespaceOptions:
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: "{{ .name }}"
  resourceQuotas:
    scope: Tenant
    items:
      {{- range .resourceQuotas.items }}
      - hard:
          {{- range $key, $value := .hard }}
          {{ $key }}: "{{ $value }}"  # Removed unnecessary quotes
          {{- end }}
      {{- end }}
  limitRanges:
    items:
      {{- range .limitRanges.items }}
      - limits:
          {{- range .limits }}
          - default:
              cpu: {{ .default.cpu }}  # Removed unnecessary quotes
              memory: {{ .default.memory }}
            defaultRequest:
              cpu: {{ .defaultRequest.cpu }}
              memory: {{ .defaultRequest.memory }}
            type: {{ .type }}
          {{- end }}
      {{- end }}
---
{{- $tenantName := .name }}
{{- range .namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    capsule.clastix.io/tenant: "{{ $tenantName }}"
    # capsule.clastix.io/allowed: "true"
---
{{- end }}
{{- end }}
