{{- range .Values.tenants }}
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: {{ .name }}
spec:
  owners:
    - name: system:serviceaccount:tenant-system:robot
      kind: ServiceAccount
  namespaceOptions:
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: "{{ .name }}"
  resourceQuotas:
    scope: Tenant
    items:
      {{- range .resourceQuotas.items }}
      - hard:
          {{- range $key, $value := .hard }}
          {{ $key }}: "{{ $value }}"  # Removed unnecessary quotes
          {{- end }}
      {{- end }}
  limitRanges:
    items:
      {{- range .limitRanges.items }}
      - limits:
          {{- range .limits }}
          - default:
              cpu: {{ .default.cpu }}  # Removed unnecessary quotes
              memory: {{ .default.memory }}
            defaultRequest:
              cpu: {{ .defaultRequest.cpu }}
              memory: {{ .defaultRequest.memory }}
            type: {{ .type }}
          {{- end }}
      {{- end }}
---
{{- range .namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    capsule.clastix.io/tenant: "{{ $.name }}"  # Explicitly access the tenant's name
    app.kubernetes.io/managed-by: "Helm" # Ensures Helm recognizes namespace
  annotations:
    helm.sh/resource-policy: keep # Prevents namespace deletion on uninstall
# dependsOn:
#   - tenant.yaml
---
{{- end }}
{{- end }}