{{- range .Values.tenants }}
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: {{ .name }}
spec:
  owners:
    {{- range .owners }}
    - name: {{ .name }}
      kind: {{ .kind }}
    {{- end }}
  namespaceOptions:
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: "{{ .name }}"
    {{- range .resourceQuotas.items }}
    - hard:
        {{- range $key, $value := .hard }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
    {{- end }}
---
{{- range .namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    capsule.clastix.io/tenant: "{{ $.name }}"
    app.kubernetes.io/managed-by: "Helm" # Ensures Helm recognizes namespace
  annotations:
    helm.sh/resource-policy: keep # Prevents namespace deletion on uninstall
---
{{- end }}
{{- end }}

