tenants:
# Tenant-1 config
  - name: tenant-id1
    namespaces:
      - tenant-id1-dev
      - tenant-id1-uat
      - tenant-id1-prd
    owners:
    namespaceOptions:
      quota: 3
    resourceQuotas:
      items:
        - hard:
            requests.cpu: 4
            requests.memory: 8Gi
            limits.cpu: 8
            limits.memory: 16Gi
        - hard:
            pods: 10
    limitRanges:
      items:
        - limits:
            - default:
                cpu: 500m
                memory: 512Mi
              defaultRequest:
                cpu: 100m
                memory: 10Mi
              type: Container
              
# Tenant2 config
  - name: tenant-id2
    namespaces:
      - tenant-id2-dev
      - tenant-id2-uat
    owners:
    namespaceOptions:
      quota: 3
    resourceQuotas:
      items:
        - hard:
            requests.cpu: 2
            requests.memory: 4Gi
            limits.cpu: 4
            limits.memory: 8Gi
        - hard:
            pods: 10
    limitRanges:
      items:
        - limits:
            - default:
                cpu: 500m
                memory: 512Mi
              defaultRequest:
                cpu: 100m
                memory: 10Mi
              type: Container
              
# Tenant3 config
  - name: tenant-id3
    namespaces:
      - tenant-id3-dev
      - tenant-id3-uat
    owners:
    namespaceOptions:
    resourceQuotas:
      items:
    limitRanges:
      items:
      
# Tenant4 config
  - name: tenant-id4
    namespaces:
      - tenant-id4-dev
      - tenant-id4-uat
    owners:
    namespaceOptions:
    resourceQuotas:
      items:
    limitRanges:
      items:
