tenants:
# Tenant1 config
  - name: tenant1
    namespaces:
      - tenant1-dev
      - tenant1-prod
    owners:
    namespaceOptions:
      quota: 3
    resourceQuotas:
      items:
        - hard:
            requests.cpu: 4
            requests.memory: 8Gi
            limits.cpu: 8
            limits.memory: 16Gi
        - hard:
            pods: 10
    limitRanges:
      items:
        - limits:
            - default:
                cpu: 500m
                memory: 512Mi
              defaultRequest:
                cpu: 100m
                memory: 10Mi
              type: Container
# Tenant3 config
  - name: tenant3
    namespaces:
      - tenant3-dev
      - tenant3-prod
    owners:
    namespaceOptions:
      quota: 3
    resourceQuotas:
      items:
        - hard:
            requests.cpu: 2
            requests.memory: 4Gi
            limits.cpu: 4
            limits.memory: 8Gi
        - hard:
            pods: 10
    limitRanges:
      items:
        - limits:
            - default:
                cpu: 500m
                memory: 512Mi
              defaultRequest:
                cpu: 100m
                memory: 10Mi
              type: Container


